### ISSUE TITLE
Running sen2cor alone

### ISSUE THREAD

**Issue by RAJohansen** [ranghetti/sen2r#108]
I am trying to run sen2cor in isolation from the GUI. I have the entire imagery downloaded from the scihub in an unzipped folder "S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342" located in "C:/temp". However I still am having a hard time interpreting how to run the sen2cor function. 

I am trying to follow your example:
**sen2cor(names(example_s2_list)[1], l1c_dir=tempdir(), outdir=tempdir())**

What exactly is the l1c_prodlist argument looking for?
1. the entire .safe folder ("C:temp/S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342")

2. list of the locations of the IMG_DATA ("C:/temp/S2A_MSIL1C...GRANULE...IMG_DATA"), 

3. list of the actual jp2 files themselves? 

Everything I have tried results in "Warning message: No valid L1C products were found"

Sorry for the many issues, but your package is great and would benefit my work a lot once I am actually able run the sen2cor correction in R.

Thanks again for the help,
Richard

**Comment by ranghetti** [comment]
Dear @RAJohansen,
`example_s2_list` is the path of the unzipped SAFE product, without parent directories, which must have the same name of the zip archive; so, in the case of the archive **S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342.SAFE.zip**, it should be **S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342.SAFE**, not **S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342**.

Sometimes, when manually unzipping an archive, a parent directory is created; in your case, you should check if your directory contains a subdir **S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342.SAFE**; if so, launch `sen2cor("C:/temp/S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342/S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342.SAFE")`.

Otherwise, if **S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342** is the parent directory of the product (containing **AUXDATA**, **DATASTRIP**, **GRANULE**, etc.), you should 
1. rename **S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342** to **S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342.SAFE**;
2. launch `sen2cor("C:/temp/S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342.SAFE")`

I will update the documentation of the function to clarify it.
Another thing which I will point out is that, on Windows, the output of the console of sen2cor is not printed out; so you will not see any output while sen2cor is running (taking more or less 45 minutes). This is normal.

Let me know if this works for you.
Thank you for testing the package, your feedbacks are very useful for me to improve the package.

**Comment by RAJohansen** [comment]
@ranghetti 

I am running (I think) the sen2cor as you suggested, but it only worked when the shiny app remained opened. Is this the intended design? 

When the shiny app was closed I received the error as before.
> sen2cor("C:/temp/S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342/S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342.SAFE")
Warning message:
 No valid L1C products were found.

**Comment by RAJohansen** [comment]
Making progress.

> sen2cor("C:/temp/S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342.SAFE")
Error in { : task 1 failed - "'--refresh' not found"
In addition: Warning message:
 This function does not work on Windows systems.

**Comment by RAJohansen** [comment]
Making progress.

> sen2cor("C:/temp/S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342.SAFE")
Error in { : task 1 failed - "'--refresh' not found"
In addition: Warning message:
 This function does not work on Windows systems.

**Comment by ranghetti** [comment]
In relation to the first version of your message:

> I am running (I think) the sen2cor as you suggested, but it only worked when the shiny app remained opened. Is this the intended design?
> 
> When the shiny app was closed I received the error as before.
> 
> ```
> sen2cor("C:/temp/S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342/S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342.SAFE")
> Warning message:
> No valid L1C products were found.
> ```

If it will appear in future, ensure that the structure of the SAFE is right. In particular, I saw problems in the past using SAFE products downloaded from [Google Cloud Storage](https://cloud.google.com/storage/docs/public-datasets/sentinel-2).

This should be the first level structure of your SAFE, without intermediate directories:
```
S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342.SAFE/
├── AUX_DATA
├── DATASTRIP
├── GRANULE
├── HTML
├── INSPIRE.xml
├── manifest.safe
├── MTD_MSIL1C.xml
└── rep_info
```

You can use `s2_download()` to download the SAFE in the right format:
```r
your_safe <- "https://scihub.copernicus.eu/dhus/odata/v1/Products('dc04a967-e338-4be7-ad2c-4ac9e507abba')/$value"
names(your_safe) <- "S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342"
file.rename(
  "C:/temp/S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342.SAFE", 
  "C:/temp/S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342.SAFE.old"
)
s2_download(your_safe, outdir = "C:/temp")
```

**Comment by ranghetti** [comment]
Regarding the second task:
> Making progress.
> ```
> sen2cor("C:/temp/S2A_MSIL1C_20180609T161901_N0206_R040_T16SGJ_20180609T194342.SAFE")
> Error in { : task 1 failed - "'--refresh' not found"
> In addition: Warning message:
> This function does not work on Windows systems. 
> ```

This should be related to #105 (the path of sen2cor executable is not correctly recognised); by reinstalling the package and the dependencies, you should solve.

Let me know,

**Comment by RAJohansen** [comment]
Reinstalling the package and the dependencies worked. I was able to successfully run the sen2cor package and produce atmospherically corrected imagery.

Thank you for your hard work!
