### ISSUE TITLE
Manage ZIP SAFE as zip archives (compact prods)

### ISSUE THREAD

**Issue by ranghetti** [ranghetti/sen2r#158]
- [ ] implement reading from SAFE mixed zip files and directories  using the [starsdata package](https://r-spatial.github.io/stars/articles/stars2.html);
- [ ] edit `s2_download()` allowing not to unzip SAFE (compact format);
- [ ] edit all the intermediate functions to recognise existing SAFE zip together with directories.

**Comment by micha-silver** [comment]
Thankyou

**Comment by sanmaral** [comment]
Dear ranghetti, I am having problems with some downloads made with s2_download (with default settings).

Sometimes the zip file does not decompress correctly. In some of these cases, the zip does not disappear after unzipping (failed), and I have the chance to unzip it manually with success. In other cases, however, the downloaded zip is deleted after unzipped (failed), and I no longer have the option to unzip it manually.

I write it here because I think it could be solved with the enhancement "edit s2_download() allowing not to unzip SAFE (compact format);".

Thanks

**Comment by ranghetti** [comment]
@sanmaral currently I have no time to implement this and other ehancements (moreover, this implementation would be more difficult to perform after the implementation of the download from google Cloud, for this reason I am also going to close this issue). Please open a new issue with the "Help needed" template, and _carefully follow the indications listed in the template_, providing all the required details.
