### ISSUE TITLE
Match between band numbers in Sentinel-2 original imagery and proceed by sen2r

### ISSUE THREAD

**Issue by Leprechault** [ranghetti/sen2r#208]
I'm so astonished with this amazing package, improves a lot my work, but I have one technical question. I have 11 bands in my processed image by sen2r package () as follow:

sen2r(
&nbsp; gui = FALSE,
&nbsp; timewindow = c(as.Date("2019-09-05"), Sys.Date()),
&nbsp; extent = "C:/Users/fores/Documents/S2_Euca/border_B_latlong.shp", extent_name = "Myextent",
&nbsp; list_prods = c("BOA"),
&nbsp; res_s2 = "10m",
&nbsp; mask_type = "cloud_and_shadow",
&nbsp; max_mask = 10, mask_smooth = 5, mask_buffer = 5,
&nbsp; extent_as_mask = TRUE,
&nbsp; path_l1c = "C:/Users/fores/Documents/S2_Euca/", path_l2a = "C:/Users/fores/Documents/S2_Euca/", path_out = "C:/Users/fores/Documents/S2_Euca/"
)

But original Sentinel-2 imagery have 13 bands. My question is why I have 11 bands in my final image using sen2r package and which is the match between Sentinel-2 original band number and proceed by sen2r ?

Thanks in advanced,

**Comment by ranghetti** [comment]
Thank you for your appreciation.
BOA tiffs produced by sen2r are composed by 11 bands because, among the 13 Sentinel-2 bands (https://sentinel.esa.int/web/sentinel/user-guides/sentinel-2-msi/resolutions/radiometric), 

1. band 10 is missing from Level-2A products;
2. bands 8 and 8a are alternatively present (band 8 if the output resolution is < 20m, band 8a if >= 20m).

For the same reason, TOA products have 12 bands (band 10 is present, and band 8 / 8a are alternatively present).

The band order is by wavelength (corresponding to band number order).
Unfortunaltely I am not able to add band name and wavelength to output geoTIFFs, but, choosing an ENVI output, this information is included in the header file.

**Comment by Leprechault** [comment]
Very clear explanation, thanks very much!!!!

**Comment by Ioannis-Faraslis** [comment]
Thanks for the quick answer and also for the very useful tool, but I would like to comment that ESA's level two (Level-2A) product has 12 bands (B8 and B8A as well) (please see the attached file) 
![sen2r_L2A](https://user-images.githubusercontent.com/62997735/78159705-95a1ce80-744b-11ea-904c-a38cf52b0f4f.jpg)
so that  I can apply the Biophysical  Processor at SNAP (LAI, FAPAR, ...etc) with no problem, in contrast to the sen2r product as I mentioned previously. Thanks again for your clarifications

**Comment by ranghetti** [comment]
Answered in #298.
