### ISSUE TITLE
Allow to leave SAFE file zipped in s2_download

### ISSUE THREAD

**Issue by micha-silver** [ranghetti/sen2r#244]
Enhancement request:
Would you consider to add a flag to s2_download to leave the downloaded Sentinal files zipped, rather than unzip into the *.SAFE directory?
My workflow will use the R package `gdalcubes `to process data downloaded by `sen2r`. But `gdalcubes`, it seems, is able to open and correctly read the zipfile, whereas the *.SAFE directory is ignored.

I tried to implement this change to s2_download.R and rebuilt the package, but I couldn't get it to work :-(
A diff of my attempt is attached.
[s2_download.txt](https://github.com/ranghetti/sen2r/files/3908667/s2_download.txt)

Thanks

**Comment by ranghetti** [comment]
This enhancement was already planned (see #158). To implement that, it is not sufficient to manage function `s2_download()`, since the whole workflow managed by `sen2r()` must be changed to deal with SAFE.zip files (but more importantly, with a mixed archive containing both zip files and directories).

You can follow the issue #158 to know when it will be implemented (I am closing this one).
