### ISSUE TITLE
Missing Band Sen2r Output 

### ISSUE THREAD

**Issue by PhuntshoPhuntsho** [ranghetti/sen2r#248]
In the Sen2r atmospheric corrected BOA output, Band 8A vegetation red edge band is missing. Comparing Sen2r BOA output with SNAP processed 2A output with their corresponding  bands reveals that band 8A is completely missing and band 9 values differs drastically than rest of the bands.

**Comment by ranghetti** [comment]
Band 8A is missing because BOA products includes alternatively band 8 or 8A repending on the resolution (see #208 and #176). This is partially documented in the GUI; online documentation will be updated as soon as a usage vignette will be ready.

Regarding band 9 issue, what do you mean with "differs drastically"? Please post a reproducible example of that.

**Comment by PhuntshoPhuntsho** [comment]
Than you for clarification about the missing Band 8A. Regarding band 9, I have compared the sen2r output band 9 pixel values with that SNAP processed sen2cor output values and they were showing large difference.  Attached screen shot of my comparison.
![Sen2r](https://user-images.githubusercontent.com/30888147/70626081-06667600-1c24-11ea-946b-01e6efc8b47b.jpg)

**Comment by ranghetti** [comment]
Sorry for late reply (I have little time to pursue this until next year).
sen2r simply launches Sen2Cor algorithm without changing any parameter. Version installed is 2.5.5 (unless you specified differently during installation). So I think differences could be due to 1. a different Sen2Cor version installed within SPAN (2.8.0); 2. a different parametrisation performed in SNAP.

You can try to investigate that by yourself:
1. working on Sen2Cor parametrisation in SNAP (I never did it, so in this moment I can nnot suggest you how to do it), or 
2. installing Sen2Cor 2.8.0 in sen2r (specifying `version = "2.8.0"` in `install_sen2cor()` - see [documentation](http://sen2r.ranghetti.info/reference/install_sen2cor)) and trying rerunning Sen2Cor to see if output values changed.

I am sorry I can not do it at this time. If you will perform these tests, let me know your results.
Thanks,

**Comment by ranghetti** [comment]
I noticed right now this setting in the `L2A_GIPP.xml` file of Sen2Cor, which should be the reason of the difference you noticed:
```xml
      <WV_Correction>1</WV_Correction>
      <!-- 0: No WV correction, 1: only 940 nm bands, 2: only 1130 nm bands , 3: both regions used during wv retrieval, 4: Thermal region -->
```
You can check if SNAP does not perform this correction by default.

Please let me know if this helps you,

Ps. I did not find any relevant information regarding water vapour correction in the [Sen2Cor
Configuration and User Manual](http://step.esa.int/thirdparties/sen2cor/2.5.5/docs/S2-PDGS-MPC-L2A-SUM-V2.5.5_V2.pdf); you can chek it by yourself to deeply investigate the matter.

**Comment by ranghetti** [comment]
@PhuntshoPhuntsho, have you verified if changing the `WV_Correction` solves the output difference?
Let us know, thanks.
