### ISSUE TITLE
Error: Sen2Cor was not found here

### ISSUE THREAD

**Issue by ranghetti** [ranghetti/sen2r#272]
_Issue received by email_

> I came across your sen2r package today, and tried to install it in Windows. I would like to have a bit of help here.
>
> When I tried to install sen2Cor, I cannot install it properly. I checked Sen2Cor software release note. I went to terminal and ran `L2A_Process.bat --help`. This returned the expected result in terminal. When I tried to select Sen2Cor with your Shiny help, I get "(Sen2Cor was not found here)". Sen2Cor is staying in Documents. I am trying to install version 2.5. What am I doing wrong? Could you tell me what to do? Thank you very much.

**Comment by ranghetti** [comment]
Hi Kota,

I need some more information to understand your problem.
1. How have you installed / linked Sen2Cor in / to sen2r? 
    - If using the GUI `check_sen2r_deps()`, describe the passages you performed to install / link it;
    - if using `install_sen2cor()` or `link_sen2cor()`, report the exact command you used.
2. Report the full path of your Sen2Cor folder and its content.
3. Paste the output of the command `load_binpaths()`.

Thanks,

**Comment by Jazzurro** [comment]
Hi Luigi,

Thank you for opening up this issue for me. I invested a few days to see if I can solve this issue. But I could not find any solution by myself. I leave the following information. If you need further information please let me know.

**1. How have you installed / linked Sen2Cor in / to sen2r?**

I went to [this link](http://step.esa.int/main/third-party-plugins-2/sen2cor/sen2cor_v2-5-5/) and downloaded a zip file for Windows. I made sure that I get version 2.5 since it is recommended. I extracted the file and put the folder in my Documents folder (`C:\Users\jazzurro\Documents\Sen2Cor-02.05.05`). Then, I read [this manual](http://step.esa.int/thirdparties/sen2cor/2.5.5/docs/S2-PDGS-MPC-L2A-SRN-V2.5.5.pdf). On page 34, there was a way to check if Sen2Cor is ready to process. I went to Terminal and accessed my directory, the folder above, and ran `C:\Users\jazzurro\Documents\Sen2Cor-02.05.05>L2A_Process.bat --help`. I got the expected message in Terminal.

![luigi01](https://user-images.githubusercontent.com/6638656/74116244-0a981b00-4bf6-11ea-94a2-605b1b230164.png)

Given this, I started an R Session with the sen2r package. I used `check_sen2r_deps()` and tried to set up Sen2Cor with the popped up window. This is the window that I had. 

![luigi02](https://user-images.githubusercontent.com/6638656/74116367-98740600-4bf6-11ea-930e-3d0baf0c3334.png)

When I pressed 'Select', I got this message.

![luigi03](https://user-images.githubusercontent.com/6638656/74116428-d7a25700-4bf6-11ea-9d27-a22b68085416.png)

Finally, I have not used `install_sen2cor()` or `link_sen2cor()` yet. The following is my session information.

![luigi04](https://user-images.githubusercontent.com/6638656/74117058-9b242a80-4bf9-11ea-8bd7-184f1789b64e.png)


**2. Report the full path of your Sen2Cor folder and its content.**

The full path is the one I mentioned in the previous question. (`C:\Users\jazzurro\Documents\Sen2Cor-02.05.05`) I used Terminal and created a text file (listing.txt) to print the contents of this folder.

![luigi05](https://user-images.githubusercontent.com/6638656/74117178-2998ac00-4bfa-11ea-9159-b86a11428982.png)

**3. Paste the output of the command load_binpaths().**

Here is the requested information that I saw in my R Console.

![luigi06](https://user-images.githubusercontent.com/6638656/74117378-c6f3e000-4bfa-11ea-8dce-295d1e897442.png)


I hope I am providing all requested information for you. Thank you very much for your kind support.

**Comment by ranghetti** [comment]
Thank you for your detailed feedback, thish helped me to understand the problem.
There was a bug in the code, fixed with commit ae0a7a9c5829ad04a84dd12446ddbefec0d537e6. You can reinstall the package from GitHub:
```r
remotes::install_github("ranghetti/sen2r")
```
Alternatively, if you do not want to reinstall the package, you can install Sen2cor from the GUI (choosing "Install a new Sen2Cor environment)"  instead than linking the existing environment (this was not bugged).

Let me know, best regards,

**Comment by Jazzurro** [comment]
Hi Luigi, thanks for your quick reply. I reinstalled your package now and tried if I can set you Sen2Cor with the sen2r package. Now I see the following. So I believe everything is set up.

![luigi](https://user-images.githubusercontent.com/6638656/74143280-e2cca580-4c3d-11ea-8942-d7fd47b32167.png)

Once again, thanks for your support.

**Comment by ranghetti** [comment]
Yes, it should be ok. If you will encounter further problems applying Sen2Cor, feel free to open a new issue.
