### ISSUE TITLE
Indices request

### ISSUE THREAD

**Issue by OterLabb** [ranghetti/sen2r#282]
Hi, im wondering if its possible to add a couple of water quality indices, mainly turbidity and Chlorophyll concentration like the ones that are used in this guide from copernicus. Could not find them in the list :) https://workshop.copernicus.eu/sites/default/files/content/attachments/ajax/mapping_of_coastal_water_quality.pdf (page 35 and 39)

Where turbidity is:
![image](https://user-images.githubusercontent.com/7389562/75255231-e20d4500-57e1-11ea-9f3c-7ff497de300a.png)
and for clhorophyll consentration:
![image](https://user-images.githubusercontent.com/7389562/75255280-f5201500-57e1-11ea-92e6-e80c69dc6e85.png)

**Comment by ranghetti** [comment]
Hi, I will do it in the next days.

**Comment by ranghetti** [comment]
I added the following two indices:
- CCI ("Chlorophyll Concentration Index"): `exp(-0.335+0.01663*(log(band_2/band_4)))`
- TI-100 ("Turbidity Index / 100"): `(1030*power(band_4,1.08)/7+0.5)/100`

The reason for which I divided TI by 100 is that its range resulted [0, 147.64] in a default [0, 1] reflectances range (which actually in L2A products can reach higher values due to "wrong" corrections of cloudy surfaces). The default output format ("Int16") is obtained multiplicating the index value by 10000: using the standard TI range, output values would result flattened on the maximum Int16 accepted value (32767). This correction was not done for CCI, whose range resulted [0, 0.74].

To test these indices, install the `feature/issue282` development branch:
```r
remotes::install_github("ranghetti/sen2r", ref = "feature/issue282")
```

Then, you can use both `s2_calcindices()` and `sen2r()` to compute them. If you make use the sen2r GUI, check "Show only verified indices" to visualise CCI and TI-100.

Please, test this feature (including the formula listed above) and give me a feedback about the validity of the outputs: after that, I will move it in the master package version and check indices as validated.

**Comment by OterLabb** [comment]
Thank you very much, I will test soon and compare results I get from SNAP

**Comment by ranghetti** [comment]
Hi @OterLabb,
did you test if the two indices are ok?
Let me know,

**Comment by ranghetti** [comment]
I am releasing the new version 1.3.3, which will not contain the two new indices since I did not receive your feedback yet.
I look forward for it in order to add these indices in the next release.

**Comment by ranghetti** [comment]
The branch `feature/issue282` was removed due to inactivity.
