### ISSUE TITLE
sen2r() for specific band, lossless download and one quality tile from a range of date

### ISSUE THREAD

**Issue by kpmainali** [ranghetti/sen2r#289]
While using the function sen2r(), how do I input the arguments/parameters for the following: 
(1) I need to download only certain bands. How do I download only the bands that I am looking for (e.g, band # 6,7,11,12)? 
(2) The function saves layers in jp2 format. Is it a lossy or lossless format? Any idea how much space I save with this compression? Can I save it in other formats without compression, such as tiff?
(3) If I need just one layer from a season, what is the best way to find the highest quality layer? If I assign a range of dates that downloads for all dates for which the condition of max_mask meet. From there, I can select data for one date. With a more efficient strategy, I would not have to download all layers to finally keep one.

Thank you.

**Comment by ranghetti** [comment]
1. You can not: sen2r functions save reflectance rasters as multiband GeoTIFF or ENVI files, containing all the bands. The package is structured in order to download the whole SAFE source products as zip archives, so it is not possible to download only the required bands.
2. `sen2r()` saves output products as GeoTIFF or ENVI, not JP2, which is instead used in input SAFE archives (this format applies a higher compression than GeoTIFF, although being lossless).
3. This is a post-processing analysis for which there are no functions in sen2r. You could use, as a criteria, the cloud coverage of SAFE images: e.g., to select only the images completely not cloud covered you could set `max_cloud = 0` in `s2_list()` or `max_cloud_safe = 0` in `sen2r()`, and use one of the _n_ returned images. But for a finer selection of the "best" image, you should define your own methodology.

**Comment by kpmainali** [comment]
Thank you. That was helpful.
