### ISSUE TITLE
Missing Band Sen2r at 560.0 nm

### ISSUE THREAD

**Issue by Ioannis-Faraslis** [ranghetti/sen2r#298]
After the creation of BOA corrected image I would like to
create biophysical parameters but I get an error message about
the missing band at 560.0 nm. 
Why after the implementation of sen2cor one band is missing ?
Please see the attached file. 
![sen2r_issue](https://user-images.githubusercontent.com/62997735/78153070-596a7000-7443-11ea-82e2-b2063a8b77ee.jpg)

Thanks in advanced

**Comment by ranghetti** [comment]
See #208.

**Comment by ranghetti** [comment]
_Quoting from #208_

> Thanks for the quick answer and also for the very useful tool, but I would like to comment that ESA's level two (Level-2A) product has 12 bands (B8 and B8A as well) (please see the attached file)
> ![sen2r_L2A](https://user-images.githubusercontent.com/62997735/78159705-95a1ce80-744b-11ea-904c-a38cf52b0f4f.jpg)
> so that I can apply the Biophysical Processor at SNAP (LAI, FAPAR, ...etc) with no problem, in contrast to the sen2r product as I mentioned previously. Thanks again for your clarifications

The decision to include alternatively band 8 or 8A was due to the fact that they cover an overlapping spectral window; so, band 8A (finer radiometric resolution, coarse spatial one) is provided when the output spatial resolution is adequate to include it (>= 20m), otherwise band 8 is used.

I agree that this choice can be negative in some cases (e.g. using SNAP tools). I will eventually evaluate to change this behaviour in a future release, but I should carefully think how to do it in order not to affect the ackward compatibility, so this will not be an upcoming improvement.

**Comment by Ioannis-Faraslis** [comment]
Thanks for your respond!
