### ISSUE TITLE
Manually set GDAL runtime dependencies

### ISSUE THREAD

**Issue by dinkel2006** [ranghetti/sen2r#300]
I am trying to use the sen2r package in R, however, I am running into an issue with the dependencies, in particular GDAL.  Our IT department is pretty strict on what software we can and cannot download.  OSGeo4W is software that is not approved and this approval process can take months (likely longer with the coronavirus).  Is there a way to acquire this GDAL dependency without the use of the OSGeo4W software?

Thanks for any help you can provide.

**Comment by ranghetti** [comment]
You can try manually setting the paths of different GDAL binaries, so bypassing `check_gdal()` and its checks. But in this way I cannot ensure you will not encounter errors (I had added the requirement of OSGeo4W-based GDAL because, in the past, some different GDAL environments caused problems).

Nevertheless, you will need a custom installed GDAL runtime environment.

To do so, first set at least another dependency (Sen2Cor or aria2). Then, open the file `~/.sen2r/paths.json` (it is a text file). It will look like that:
```json
{
  "aria2c": ["/usr/bin/aria2c"],
  "sen2cor": ["/home/lranghetti/.sen2r/sen2cor_versions/sen2cor_255_cci/bin/L2A_Process"]
}
```

Now, edit it adding the following entries:
```json
{
  "aria2c": ["/usr/bin/aria2c"],
  "sen2cor": ["/home/lranghetti/.sen2r/sen2cor_versions/sen2cor_255_cci/bin/L2A_Process"],
  "gdalinfo": ["/usr/bin/gdalinfo"],
  "gdal_calc": ["/usr/bin/gdal_calc.py"],
  "gdal_fillnodata": ["/usr/bin/gdal_fillnodata.py"],
  "ogrinfo": ["/usr/bin/ogrinfo"],
  "gdal_translate": ["/usr/bin/gdal_translate"],
  "gdalwarp": ["/usr/bin/gdalwarp"],
  "gdalbuildvrt": ["/usr/bin/gdalbuildvrt"],
  "gdaldem": ["/usr/bin/gdaldem"],
  "gdal_polygonize": ["/usr/bin/gdal_polygonize.py"],
  "python": ["/usr/bin/python3.6"]
}
```
You must set all the paths of GDAL-related executables, using existing paths. 
This is another example on Windows (you did not specify your OS):
```json
{
  "gdalinfo": ["C:\\OSGEO4~2\\bin\\gdalinfo.exe"],
  "ogrinfo": ["C:\\OSGEO4~2\\bin\\ogrinfo.exe"],
  "gdal_translate": ["C:\\OSGEO4~2\\bin\\GDAL_T~1.EXE"],
  "gdalwarp": ["C:\\OSGEO4~2\\bin\\gdalwarp.exe"],
  "gdalbuildvrt": ["C:\\OSGEO4~2\\bin\\GDALBU~1.EXE"],
  "gdaldem": ["C:\\OSGEO4~2\\bin\\gdaldem.exe"],
  "python": ["C:\\OSGEO4~2\\bin\\python.exe"],
  "gdal_calc": ["C:\\OSGEO4~2\\bin\\python.exe C:\\OSGEO4~2\\bin\\GDAL_C~1.PY"],
  "gdal_polygonize": ["C:\\OSGEO4~2\\bin\\python.exe C:\\OSGEO4~2\\bin\\GDAL_P~2.PY"],
  "gdal_fillnodata": ["C:\\OSGEO4~2\\bin\\python.exe C:\\OSGEO4~2\\bin\\GDAL_F~1.PY"],
  "aria2c": ["C:\\Users\\LRANGH~1\\DOCUME~1\\SEN2R~1\\aria2c.exe"]
}
```
Notice that, in this case, you must
1. use short paths (use R function `utils::shortPathName()`) to obtain them);
2. in case of Python-based utilities (gdal_calc, gdal_polygonize and gdal_fillnodata), put the Python path before the GDAL path (the Python binary included in GDAL must be used).

Let me know if that will work,

Ps. I am working in these days in order to replace some GDAL runtime dependencies with internal C methods (from package **`sf`**). But I can not remove _all_ of them, since I did not find any valid replacement for `gdal_fillnodata.py` (`raster::buffer()` can do the same, but it is extremely slower).

**Comment by dinkel2006** [comment]
Looks like this will work.  Thank you for responding so quickly.


-----Original Message-----
