### ISSUE TITLE
band naming

### ISSUE THREAD

**Issue by betsadelab** [ranghetti/sen2r#305]
Congrats for such a great package, this has been quite useful for my workflows. 
Could you please specify the band names resulted from s2_translate or GUI. The BOA bands are numbered from 1 - 11. Just would like to confirm if this would be: band 2 (as 1 in BOA), 3 (as 2), …, 8 (as 7), 8a (as 8), 9 (as 9), 11 (as 10), and 12 (as 11). 
Hope this makes sense. 
Many thanks,
Betsa

**Comment by ranghetti** [comment]
Thank you for your appreciation.
See #208 for an explanation of band names, and #298 for the reason of this choice.

Since this is partially documented (only in the GUI), I am planning to improve the vignette [Output file structure](https://sen2r.ranghetti.info/articles/outstructure.html) to include information on products.

**Comment by ranghetti** [comment]
The vignette was now properly updated (https://sen2r.ranghetti.info/articles/outstructure.html#products).
