### ISSUE TITLE
Request failed [500] ordering from Long Term Archive

### ISSUE THREAD

**Issue by vrgaliano** [ranghetti/sen2r#314]
Hi, I wrote the following code below to order some S2 images that are offline, assuming that I can order them from a list iterating every 30 mins. However, I aways get an error (see bottom of the post)

time_window <- as.Date(c("2017-07-01", "2019-07-31"))
list_safe_offline <- s2_list(tile="29SQC", time_interval = time_window, availability = "lta")

# Order the products
for( k in seq_along(list_safe_offline) ) {
 s2_order(list_safe_offline[k], apihub="C:/Users/usuario/Documents/.sen2r/apihub.txt")
 Sys.sleep(30*60+1)
}

[2020-05-07 01:27:30] Check if products are already available for download...
[2020-05-07 01:27:30] Ordering 1 Sentinel-2 images stored in the Long Term Archive...
Request failed [500]. Retrying in 1 seconds...
Request failed [500]. Retrying in 1.5 seconds...
[2020-05-07 01:27:34] 1 of 1 Sentinel-2 images were not correctly ordered (HTML status
         code: 500). You can try ordering them at a later time using the command:
  s2_order("C:/Users/usuario/DOCUME~1/SEN2R~1/lta_orders/lta_20200507_012734.json")

**Comment by ranghetti** [comment]
This is a problem of the Long Term Archive infrastructure, which can not be bypassed by sen2r. There is a limiting user quota _per user_ on the orders which can be made (see #283); in addition, a limit _on the whole infrastructure_ seems to exists; in other words, if other users already made too many orders, you can not order even a single product. This is a really frustrating problem, affecting the concrete possibility to access old Sentinel-2 data.

For your interest, recently I had been able to order products on little Easter day (probably because of less inrastructure usage). You can try to repeat your order during the weekend
