### ISSUE TITLE
Multiple Tile Date Merging

### ISSUE THREAD

**Issue by dinkel2006** [ranghetti/sen2r#320]
I apologize if this has been covered in a past posting.  I am tying to get an imagery file for chlorophyll-a analysis of a very large reservoir which covers several tiles.  When pulling the images, I can find all of the appropriate tiles, however, they have different dates associated with them (within 1 week). Is there a relatively easy way to merge these tiles in sen2r, regardless of their date?

Thanks

**Comment by ranghetti** [comment]
No, because the package is designed for preprocessing operations, while merging tiles acquired in different dates (so being part of different images) is a processing operation requiring some more user decisions ( i.e. in case of overlapping images, which one should I keep? The most recent or the cleanest? Or should I fuse them in some way?)
Using the package you can merge tiles acquired in the same date to recreate images, each one with the same extent.

**Comment by dinkel2006** [comment]
Thanks for the quick response.  That’s what I figured but wanted to ask.

Thanks again,
Brent

-----Original Message-----
