### ISSUE TITLE
new feature: Biophysical parameters

### ISSUE THREAD

**Issue by VicenteYago** [ranghetti/sen2r#334]
Hi, I really like this library, but sometimes I wish it had some way of calculating biophysical parameters like the following: 

LAI, 
FAPAR, 
FCOVER

I know it's really hard to calculate.
I've seen that ESA's  SNAP platform provides a way (neural network-based http://step.esa.int/docs/extra/ATBD_S2ToolBox_L2B_V1.1.pdf) to both IDE and command line through its Graph Processing Framework (https://senbox.atlassian.net/wiki/spaces/SNAP/pages/70503590/Creating+a+GPF+Graph)

Have you ever thought of including something like this in sen2r?. 
cheers!

**Comment by ranghetti** [comment]
This could be done, and I planned to do it sooner or later; but there are two obstacles:
1. the implementation would require a lot of time (while I am currently focused on different tasks);
2. this would require to add SNAP as an external dependency, and external dependencies are the more problematic element of this package (indeed I recently focused on _removing_ current external dependencies, like GDAL - which is no more a mandatory dependency - and aria2 - whose usage is now discouraged and probably will be removed in a future release).

I leave this issue open as a reminder, but I think I will not handle it soon.

**Comment by VicenteYago** [comment]
Hi!, 
in this months I have been revolving around this, and I am interested in develop this feature  if not directly into sen2r, in a separately package looking into further integration into sen2r. 

At this point I am considering how to manage SNAP tools into R and as far I know there are 2 ways: 

- Interfacing directly from SNAP bash commands, dealing with GPT graphs. [1]
- Interfacing with oficial SNAP python libraries [2] (which are a port form original ones in java ) as was done with keras through `reticulate`[3].

I am more oriented to the second option, with dockerization as an objective to avoid dependencies problems. 

What do you think? ;)

[1]: https://senbox.atlassian.net/wiki/spaces/SNAP/pages/29261849/Command-line+Interfaces
[2]: https://senbox.atlassian.net/wiki/spaces/SNAP/pages/24051781/Using+SNAP+in+your+Python+programs
[3]: https://rstudio.github.io/reticulate/

**Comment by ranghetti** [comment]
Hi, 
I passed through {reticulate} in the first developing stage of {sen2r} to integrate Python-based GDAL executables: despite the number of users was less than the current one, several cases of problems with Python configuration occurred (you can have a look to olest Github issues to have an idea about). For this reason I would recommend you to use {reticulate} only if you are interested in building a package for your own use. Otherwise, regarding the best choice among 1 and 2, it would depend on which solution is the more exportable: if you are intereseted in releasing a public solution, remember that you will have to build it but also maintain it, and this is the hardest part of the work in terms of required hours (including the time devoted to write testing code - this is very important to avoid bugs during subsequent code updates). So, my advice is focusing on exportability, both on designing your functions and on writing accessory functions for user configuration (regarding this part, in the {sen2r} code you can find examples in the functions devoted to install and configure Sen2Cor, aria2 and GDAL (currently only Sen2Cor integration is supported - I superseded Python-GDAL and aria2 for user configuration problems - but the code is still in the reporistory).

Regarding the integration in {sen2r}, I would suggest to build a separate package: it would be easier for you both to keep updated separately and to have a personal return in terms on visibility; then you could fork {sen2r}, develop here the "linking" functions (edits to `sen2r()` to manage new products and GUI integration) and make a pull request (or I can write these parts). 

If you have further question feel free to use this task. Good luck!

**Comment by VicenteYago** [comment]
The exportability and maintenance is an undervalued topic for sure!, I will take it into account in the development of the package and  start exploring the two ways and then focus on the one that works best, I will look at the configuration files you mention, thanks for sharing your valuable experience ;)
