### ISSUE TITLE
Produce lists of images that are in the long-term archive

### ISSUE THREAD

**Issue by BJKUNS** [ranghetti/sen2r#345]
Hi!
Thank you so much for making this package and updating it. I use it a lot and find it to be the best bulk download tool for Sentinel. One issue I'm running into, however, concerns orders from the long-term archive (LTA), and here I have a couple of questions. Perhaps I am asking for an enhancement. Maybe there is a way to parse the json file to do what I need, or some other (obvious?) solution that I am missing. 

I'm making orders (using the s2_list and s2_download) that stretch over an entire growing season for both Level 1C and Level 2A for 2019. This means that I inevitably have to retrieve some images from the LTA. If I haven't exceeded the maximum number of images that I can order from the LTA from my account, I of course get the json file which can be used a little later in the safe_is_online command, to see if the files are available online. So the safe_is_online command can tell me how many of the images from the original s2_download attempt are online. The problem is that a lot of those images are slow to be put online and some never get online. Meanwhile, if I wait too long, images that were put online based on my order start to disappear. This is -- if I understand correctly -- a Copernicus issue and not an issue with Sen2r. However, I wonder if there could be an option to get a safelist for the images that need to be ordered from the LTA, instead of automatically ordering them. Then, if I understand correctly, I could use that safelist to separately order the images in the LTA, using s2_order. I think this would make it easier to keep track of the files that I lack. Perhaps I can I do this by myself by parsing the json file that results from the s2_download command where LTA images are automatically ordered? If so, I'll explore that option. Maybe there is another obvious solution to my issue that I am just missing, in which case, I apologize for troubling you with this question/feature request.

**Comment by ranghetti** [comment]
Hi,
thank you for your appreciation.
You can use `s2_list()` with the argument `availability = "check"` (see [the documentation](https://sen2r.ranghetti.info/reference/s2_list)). For example:
```r
pos <- sf::st_sfc(sf::st_point(c(9.85,45.81)), crs = 4326)
time_window <- as.Date(c("2016-05-01", "2017-07-30"))

example_s2_list <- s2_list(
  spatial_extent = pos,
  tile = "32TNR",
  time_interval = time_window,
  orbit = "065",
  availability = "check"
)
```
This returns a `safelist` object which includes the attribute `online`, which can be used to discriminate online products from LTA ones. The easiest way to do it is to convert the `safelist` in a `data.table`, filter it and then re-convert in a `safelist`:
```r
# List of SAFE not available online
as(as.data.table(example_s2_list)[online==FALSE,], "safelist")
```

Being in your situation, some time ago I prepared a script with a `while` cycle, running every 6 hours: every time, the script was checking for products available online, ordering the missing ones and downloading the ones which were made available. In this way I was able to download them (with a lot of patience, due to the limitation of the LTA infrastructure - see #314).

**Comment by BJKUNS** [comment]
Excellent! Thank you so much for your answer! This helps a lot.
