### ISSUE TITLE
Output filename [...]2Ap[...]T11SNR

### ISSUE THREAD

**Issue by lachmoeve** [ranghetti/sen2r#357]
Hello, 
If I have seen it right, yet nobody else had my problem. I am using Windowns 10 and R version 4.0.2. With the command remotes::install_github("ranghetti/sen2r") I have installed the latest version of sen2r.

Some output files of sen2cor used in sen2r have the ending T11SNR. I am wondering what this means. According to the log-file it seems as if atmospheric and terrain correction was applied. So what does this ending mean? Does it give a hint that something went wrong? 

I would be very thankful for any kind of help or advise. Greetings

**Comment by ranghetti** [comment]
Can you provide a reproducible example (https://github.com/ranghetti/sen2r/issues/186)?

**Comment by lachmoeve** [comment]
[SessionInfo_Version_Binpaths.txt](https://github.com/ranghetti/sen2r/files/5497270/SessionInfo_Version_Binpaths.txt)
[Sen2_Download_2.txt](https://github.com/ranghetti/sen2r/files/5497272/Sen2_Download_2.txt)

[S2A_MSIL2A_20171217T182751_N0206_R127_T11SNR_20171217T200555_20200928T043234_report.txt](https://github.com/ranghetti/sen2r/files/5497293/S2A_MSIL2A_20171217T182751_N0206_R127_T11SNR_20171217T200555_20200928T043234_report.txt)

**Comment by lachmoeve** [comment]
I also wanted to load the downloaded images but it said that those don't have the right filetype.

**Comment by ranghetti** [comment]
If I understood correctly, the suffix "T11SNR" appears:
1. opening files with ENVI, not in the output file name;
2. in the Level-2A SAFE produced by Sen2Cor, not in the files produced by sen2r.

Do you confirm that?

Moreover, does this suffix create you problems, or is it a simple question? This because I am seeing that:
a) you are using a preoperational product (2Ap), so it is possible that the Sen2Cor output metadata are different from operational level-2A products; 
b) 11SNR is the tile you set in the sen2r json parameter file.

**Comment by lachmoeve** [comment]
1) Not exactly: This is for eample the name of one of ther folders that was created: S2A_MSIL2A_20171207T183301_N0206_R127_T11SNR_20171207T195809.SAFE

2) Those products have been produced by sen2Cor via sen2r. 

Moreover, does this suffix create you problems, or is it a simple question?
I didn't have a problem yet, I was just curious and wondering why this happens. I wanted to know if those different names might be an indicator for a problem that I haven't noticed. Actually, I downloaded all data from 2015 until 2020 of my region of interest using the same json file and I have several images changing their names in ENVI from the one mentioned above to just 
10m-S2MSI2Ap 2015-08-10 18:33 or to 
10m-S2MSI2A 2019-01-21 18:26 T11SNR 

a) Indeed I have also noticed the 2Ap version of the image. But if I am not mistaken I have to keep it in mind but I can not do much about it. 
See: https://forum.step.esa.int/t/processing-level-2a-vs-2ap/12699

b) Oh, I did not know/ haven't seen that. Thank you! So if this is just the name of the tile, I guess it shouldn't be a problem, right?

**Comment by ranghetti** [comment]
> 1. Not exactly: This is for eample the name of one of ther folders that was created: S2A_MSIL2A_20171207T183301_N0206_R127_T11SNR_20171207T195809.SAFE

This is the name of the SAFE archive in the standard format. All SAFE archives packaged in the "compact" format (which is the standard since three years) have the tile ID in the name. You can notice that also the other SAFE archives have the same structure (with the exception of the ones in the "old" format, which you can have on your machine only in the case you downloaded them some years ago).

> 2. Those products have been produced by sen2Cor via sen2r.

Yes, bot sen2r simply launches Sen2Cor. What Sen2Cor does is a "black box" for sen2r.

> I didn't have a problem yet, I was just curious and wondering why this happens. I wanted to know if those different names might be an indicator for a problem that I haven't noticed. Actually, I downloaded all data from 2015 until 2020 of my region of interest using the same json file and I have several images changing their names in ENVI from the one mentioned above to just
> 10m-S2MSI2Ap 2015-08-10 18:33 or to
> 10m-S2MSI2A 2019-01-21 18:26 T11SNR

Unfortunately I do not use ENVI, so I do not know what it uses to produce labels. If you notice differences about SAFE folder names I can answer you, but not about ENVI labels.

> b) Oh, I did not know/ haven't seen that. Thank you! So if this is just the name of the tile, I guess it shouldn't be a problem, right?

I suppose so (in fact, I am more surprised that some products does not include that; but again, I do not know ENVI).

**Comment by lachmoeve** [comment]
Ok, thanks that helped a lot.
