### ISSUE TITLE
How do you specific a geographic projection instead of UTM

### ISSUE THREAD

**Issue by eblanc** [ranghetti/sen2r#369]
Hi,
I would like to obtain VI indices with geograpic project (WGS 1984 with lat and lon in decimal degrees) instead of UTM. How do you specify that ? I tried the EPSG 4326 but it still remians in UTM. Thanks!

**Comment by ranghetti** [comment]
Hi, geographic projection can be set both in the GUI and with the `sen2r()` argument `proj`.

In order to understand why it remains in UTM in your case, you had to fill the issue template with the required information instead than deleting it, as clearly stated in the first sentence of the template:

> IMPORTANT NOTE: the following template must not be deleted, but read and filled with the required information. Issues written without following the template will be marked as "malformed" and ignored.

Please do it.
