### ISSUE TITLE
How can I choose a single satellite image among the available data within the time interval I specify in GUI?

### ISSUE THREAD

**Issue by Zavud** [ranghetti/sen2r#388]
**Functionality**
Hi. I am using the GUI version of the package and when I need to download data I usually choose the "Temporal range" of my interest within a month. For example, if I need data from September, I will specify the time range to be "September 1 to September 30". If there are multiple images available for this range, I will need to download all the data, rather than choosing only one of the data that suit my needs the most. Is there a way (using the GUI) to choose a specific image among the available images? Thanks.

**Documentation reference**
 I read  [the web page](http://sen2r.ranghetti.info/) but I could not find information about this specific question.

**Comment by ranghetti** [comment]
No, there is not this functionality, and this is intentional, since {sen2r} was though to facilitate the processing of multiple images and the creation of archives useful for time series analysis. Conversely, the functionality you required already exist using [SciHub](https://scihub.copernicus.eu/dhus/#/home) or other commercial interfaces. 
If you want to use {sen2r} to process specific images you can go on SciHub, browse images and select the most suitables; download them and then launch `sen2r()` in offline mode (in this way only the downloaded images will be processed). Or you can select images on SciHub and download/process them with `sen2r()` specifying the dates you selected.

**Comment by Zavud** [comment]
@ranghetti thank you for letting me know this. Using the GUI in offline mode in this case sounds like a great idea!
