### ISSUE TITLE
upcoming sf will break sen2r

### ISSUE THREAD

**Issue by edzer** [ranghetti/sen2r#396]
Please see https://github.com/r-spatial/sf/issues/1649 and consider commenting there in case you run into troubles. I see another invalid geometry, (Cc @paleolimbot):
```
Running examples in ‘sen2r-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: tiles_intersects
> ### Title: Select the tiles intersecting the extent
> ### Aliases: tiles_intersects
>
> ### ** Examples
>
> ex_extent <- sf::st_read(
+   system.file("extdata/vector/scalve.kml", package = "sen2r"),
+   quiet = TRUE
+ )
> ex_extent <- ex_extent[1,]
>
> # Tile ID of the required S2 tile
> tiles_intersects(ex_extent)
Error in s2_geography_from_wkb(x, oriented = oriented, check = check) :
  Loop 0 is not valid: Edge 0 is degenerate (duplicate vertex)
Calls: tiles_intersects ... as_s2_geography.WKB -> new_s2_xptr -> s2_geography_from_wkb
Execution halted
```

**Comment by edzer** [comment]
I looked into the code where this breaks. (Interesting btw you also use the `s2_` prefix - luckily there are no name clashes so far with the `s2` package!) My guess is that the geometries in `s2_tiles()` are meant to be interpreted in an R2 long/lat space (plate carree) rather than on the sphere, as that is how they are aligned: on a long/lat rectangular grid. You can get the "sf classic" behaviour by different options:
* set `sf_use_s2(FALSE)` - but that must be set back to the starting condition, as it changes everything for the rest of the R session
*  by  `st_crs(.s2_tiles) = NA` (and for the other geometry too) which means `sf` will directly assume R2 & call the GEOS routines.
* by transforming to `+proj=eqc` (but that changes coordinate values)

The second option sounds ugly, but is probably the most robust / safe one. It will also work with current sf.

**Comment by ranghetti** [comment]
Currently, function `s2tiles()` download the vector https://github.com/ranghetti/sen2r/blob/master/utils/vector/s2_tiles.rds (too big to be included in the package), created from the official grid of the Sentinel-2 tiles using this code: https://github.com/ranghetti/sen2r/blob/a2e72be00d34f2e38a22f296715cb8b669af7c73/R/s2_tiles.R#L51-L64

So the original CRS (EPSG:4326) was maintained, but you are right that this is wrong. In fact, each cell of the grid is meant to be interpreted in the UTM coordinates corresponding to its zone... For this reason, also using Plate Carrée would not be correct (cells do not perfectly overlap with the corresponding Sentinel-2 images).

To manage that, I think I will modify `s2_tiles()` to deal with 60 different grids, one per UTM timezone, eventually returning a single spatial output after densifiying the grid (I cannot densify it before loading on GitHub because I would obtain a file too big). This will affect all the functions using the grid, so I need some time to do that.

In the meanwhile, to avoid breaks I have used a workaround in 60626fce15d9c47217a696ecaa8fb577e1a4849e and 1abd9c7fbdfec98be88358dcd593935328d9e8f0 adding `if (any(!st_is_valid(x))) {x <- st_make_valid(x)}` where errors could verify (geometric operations). This is quite time consuming, but for now it seems to be working (if you have different suggestions they are welcome).

If that is ok, I will submit to CRAN the current version and manage edits to `s2_tiles()` and in general to functions using geographical data later (I doubt to be able to do it before May).

**Comment by ranghetti** [comment]
sen2r 1.4.3 is on CRAN. In addition to the performed edits, I added some temporary instructions `sf_use_s2(FALSE)` as you suggested (in the form cited below) to avoid eventual future errors like https://github.com/r-spatial/sf/pull/1669: https://github.com/ranghetti/sen2r/blob/96e3ae65bec337e56a9bf1e3d836e51d4c316cbc/R/tiles_intersects.R#L56-L57

**Comment by edzer** [comment]
Great, thanks!
