### ISSUE TITLE
Processing was not completed because some required images are offline

### ISSUE THREAD

**Issue by Za1987** [ranghetti/sen2r#411]
```r
library(sen2r)
sen2r()


```

**Expected and actual behavior**

[2021-06-01 19:09:10] #### Starting sen2r execution. ####
[2021-06-01 19:09:14] Launching GUI...
Loading required package: shiny

Listening on http://127.0.0.1:3762
Registered S3 method overwritten by 'geojsonlint':
  method         from 
  print.location dplyr
[2021-06-01 19:23:10] Gui closed by the user. Starting processing.
[2021-06-01 19:23:13] Searching for available SAFE products on SciHub...
[2021-06-01 19:24:13] Ordering 9 Sentinel-2 images stored in the Long Term
       Archive...
[2021-06-01 19:24:28] 9 of 9 Sentinel-2 images were correctly ordered.
+-------------------------------------------------------------------------
¦ sen2r Processing Report
¦-------------------------------------------------------------------------
¦ Dates to be processed based on processing parameters: 2
¦ Processing completed for: 0 out of 2 expected dates.
¦ Outputs for: 2 out of 2 expected dates not created because all/some
¦ required images are currently offline.
¦ Order for: 9 out of 9 offline images successfull.
¦ You can check later if the ordered images are online with the command:
¦   safe_is_online("C:/Users/user/DOCUME~1/SEN2R~1/lta_orders/lta_20210601_192428.json")
¦ When additional images are online, you can relaunch the processing chain
¦ using the command:
¦   sen2r("C:/Users/user/DOCUME~1/SEN2R~1/proc_par/s2proc_20210601_192312.json")
+-------------------------------------------------------------------------
[2021-06-01 19:24:28] #### sen2r session terminated. ####
Warning message:
Processing was not completed because some required images are offline (see
the processing log). 

```

**Comment by ranghetti** [comment]
This is normal: something that is not available online can not be downloaded. {sen2r} can order products from LTA and downloaded them once they are made available (but not before). To conclude your processing you have to follow the indications provided in the message you posted:
```
¦ You can check later if the ordered images are online with the command:
¦ safe_is_online("C:/Users/user/DOCUME1/SEN2R1/lta_orders/lta_20210601_192428.json")
¦ When additional images are online, you can relaunch the processing chain
¦ using the command:
¦ sen2r("C:/Users/user/DOCUME1/SEN2R1/proc_par/s2proc_20210601_192312.json")
```

Read the documentation listed below to understand how the LTA policy works and how sen2r manage it:
- https://scihub.copernicus.eu/userguide/LongTermArchive (description of Sentinel-2 Long Term Archive);
- https://luigi.ranghetti.info/post/order-s2-lta/ (a post describing how to manage orders with sen2r -- notice that is quite old);
- #408 (reduction of the retention period);
- #406 (a problem caused by SciHub that is currently affecting products ordered from LTA).
