### ISSUE TITLE
Request: "Insert a optional argument to limit the download to the last 2 days"

### ISSUE THREAD

**Issue by agronomofiorentini** [ranghetti/sen2r#428]
Thanks again for developing and maintaining this package.

Is it possible to add an optional argument that could limit the downloading of the number of images?

I explain better with an example.

Defining the spatio-temporal range to make the query, it is possible to select only the 2 or more recent dates (close to end-date of the query) of the countless dates that can be found with the query in the sen2r() function.

Because right now to do so i am using the s2_list() function and then select the first 2 rows by using the head(2) and then download the images.

So at the end of the day I have performed 2 api calls.

Thanks again

**Comment by ranghetti** [comment]
I would prefer not to implement the functionality you are suggesting, for several reasons.

1. I believe it would be out of scope. The aim of the function `sen2r()` is the creation (and eventually the update) of an archive of S2-derived products, while this suggestions would be functional to obtain the "most recent clean data". In the past I intentionally avoided to implement instruments for this scope (e.g. the visualisation of the SAFE preview in the GUI), because I think that instruments like Copernicus Open Hub or Sentinel-hub already provides these tools.

2. The selection of "clean products" would be based on the percentage of cloud-free surface of the whole SAFE archive, and not of the required AOI (because downloading images would be required to compute the AOI's cloud-free surface). Implementing in `sen2r()` an argument based on SAFE an not on the AOI would be misleading (of course you can use the function `sen2r()` only to search and download, but this is not its first aim).

3. Currently I have not the possibility to make new implementations to the package (unless they are strategic, as in the case of the download from Google Cloud). In your case you can obtain what you need using `s2_list()` and `s2_download()` sequentially, without needing new implementations (you would perform the same number of calls than using `sen2r()`, because `sen2r()` internally calls `s2_list()` and `s2_download()` sequentially).
