### ISSUE TITLE
Customize final BOA name in the image created

### ISSUE THREAD

**Issue by Leprechault** [ranghetti/sen2r#432]
Hi Everyone!

After my BOA image create I have the file (`S2A2A_20160615_124_AguaSumidaPR001120160629_BOA_10.tif`) , but for me the file needs to contain the tile information `T22KDC` like in the safe directory create (`S2A_MSIL1C_20160622T133222_N0204_R081_T22KDC_20160622T133225.SAFE`). Is there any way to create a final file with this information? My desirable output is `S2A2A_20160615_124_AguaSumidaPR001120160629_BOA_10_T22KDC.tif`.
Please, any help with it?

**Comment by ranghetti** [comment]
It is not possible to do that within sen2r, basically because sen2r is though to merge adjacent tiles in order to process an AOI, so multiple tiles per AOI are possible (and so it would not be possible to add the tile in an output name because tiles could be more than one).
Moreover, changing the output name would break the [sen2r naming convention](https://sen2r.ranghetti.info/articles/outstructure.html#naming-convention).

If you know which tile is covered by your AOI you could simply call your AOI with a name which includes the tile, e.g. `AguaSumidaPR001120160629-T22KDC`.

**Comment by Leprechault** [comment]
Thanks for the feedback @ranghetti
