### ISSUE TITLE
Errors with PROJ 910 and GDAL 352 in reverse dependency checks

### ISSUE THREAD

**Issue by rsbivand** [ranghetti/sen2r#447]
[00check.log](https://github.com/ranghetti/sen2r/files/9488155/00check.log)
[testthat.Rout.zip](https://github.com/ranghetti/sen2r/files/9488158/testthat.Rout.zip)

also dev-versions of **sf**, **raster** and **terra**.  Maybe only `Problems with SciHub credentials; check secrets.` whiich obviously I will not have - I can't instrument 1000 revdep checks for all combinations of credentials. If it is only that, please modify the tests to hop over tests requiring any such credentials.

To follow up this, please install PROJ 910 (released) and GDAL 352 (now RC), dev. versions of **sf**, **raster** and **terra**, and run R CMD check with your credentials to see whether this is any of the new/dev versions, or just my not having credentials.

**Comment by ranghetti** [comment]
Sorry for the bot, but due to career change I can no longer provide assistance for the package. I will manage this as soon as possible (steamlining tests or removing the package from CRAN).

**Comment by ranghetti** [comment]
The new version [v1.5.2](https://github.com/ranghetti/sen2r/releases/tag/v1.5.2) avoids tests which made use of SciHub credentials, as well as tests which read outputs using {stars} (@rhijmans). 
Unfortunately this version, ready since a week, was not yet by CRAN because of an additional M1MAC issue (https://www.stats.ox.ac.uk/pub/bdr/M1mac/sen2r.out). e245c2355a8dce5ca62ed68cc830d1cbc7cbb02d before and bb823e2d367bdcecd1138e27ce42efa33a9e2d43 - bd14684a230aeb76ab8f672a52f66b2824ff06fc after should have fixed (macOS builder: https://mac.r-project.org/macbuilder/results/1662964150-29cce6eecbae8d05/), but I'm still receiving negative answers by CRAN maintainers (segmentation fault). I hope it will be accepted soon.

**Comment by ranghetti** [comment]
Version [1.5.3](https://github.com/ranghetti/sen2r/releases/tag/v1.5.3), which avoids using of SciHub credentials within tests, is on CRAN.
