### ISSUE TITLE
sen2r quitting with error "cloud coverage was higher than 'max_mask'"

### ISSUE THREAD

**Issue by aceresi** [ranghetti/sen2r#88]
Hi!
I was processing my S2A L2A data with:

sen2r:::geograbber_process(... , ... , mask_type = 'cloud_medium_proba', overwrite = TRUE) 

and I got this:

[2018-05-24 10:09:17] Starting sen2r execution.
[2018-05-24 10:09:20] Computing output names...
[2018-05-24 10:09:23] Updating output names...
[2018-05-24 10:09:25] Starting to translate SAFE products in custom format.
 Using UTM zone 32.
 2 output files were correctly created.
[2018-05-24 10:09:28] Execution of sen2r session terminated.
character(0)
Warning message:
 Some files were not created (probably because the cloud coverage was higher than "max_mask"):
"C:/GGdata/2018-05-22T162027_154Z/out/BOA/S2A2A_20180522_065__BOA_10.tif" 

I also tried all of the other masking options (high_proba, cloud_and_shadow, nodata), obtaining the same result. Any help?

Thanks in advance!

**Comment by ranghetti** [comment]
Hi,
the default value of `max_mask` is 100 by default, so the reason should not be related to that.
Currently that message appears for each file expected to be created and not created (being the reason related to a high cloud coverage or not). 
I planned to split the two warning sources (high cloud coverage and unexpected events) in order not to produce a misleading warning and to better monitor this kind of errors.

In the meantime, please 
1. report which input SAFE are you using;
2. download the last devel (I edited `geograbber_process()` in order to accept also additional arguments from `sen2r()` - see the help);
3. launch 
    ```r
    sen2r:::geograbber_process(
      "C:/GGdata/2018-05-22T162027_154Z",
      "C:/GGdata/2018-05-22T162027_154Z/out" , 
      overwrite = TRUE, 
      tmpdir = "C:/GGdata/2018-05-22T162027_154Z/temp",
      rmtmp = FALSE
    )
    ```
4. report which outputs are present in `tmpdir`

**Comment by aceresi** [comment]
Thank you, I tried your procedure by step and it seemed to work, at least partly, but we excluded masking. This is the result:
1. I am using S2A_MSIL2A_20180522T102031_N0207_R065_T32TNR_20180522T123546.SAFE (I don't know if this answers your question but I can't understand it)
2. Done! I had a little problem updating the whole thing. I removed the package and, as I re-installed it, I couldn't because of an error like "we miss 'httpuv' library an cannot procede any further: aborting installation"; so I manually installed 'httpuv' package and everything seemd to work. I used your GUI to check the dependencies and, when checking aria2 installation, I got a severe error and a crash of the whole Rstudio environment. I re-installed sen2r anew and just avoided to check for aria2 and everything run ok.
3. Done. It looks like it's working -- I see my BoA right where it should be, but we didn't specify the masking here
4. I have:
./temp/merged/BOA/S2A2A_20180522_065__BOA_10.vrt   (7 kB)
./temp/s2_merge/S2A2A_20180522_065__BOA_10.vrt   (7 kB)
./temp/s2_thumbnails/S2A2A_20180522_065__BOA_10_filterbands.vrt
./temp/s2_thumbnails/S2A2A_20180522_065__BOA_10_resized.vrt
./temp/s2_translate_l2a/   (empty)
./temp/tiles/BOA/S2A2A_20180522_065_32TNR_BOA_10.vrt   (8 kB)
